# Generated by Django 4.1.7 on 2023-03-30 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 8, 9, 1, 733469, tzinfo=datetime.timezone.utc)),
        ),
    ]
