# Generated by Django 4.1.7 on 2023-04-01 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 11, 59, 18, 366249, tzinfo=datetime.timezone.utc)),
        ),
    ]
