# Generated by Django 4.1.7 on 2023-04-01 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 21, 21, 50, 217769, tzinfo=datetime.timezone.utc)),
        ),
    ]
