# Generated by Django 4.1.7 on 2023-04-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activate_key_expires',
        ),
    ]
