# Generated by Django 4.1.7 on 2023-04-02 21:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
