# Generated by Django 4.1.7 on 2023-04-04 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uin',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=37, verbose_name='УИН'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='uin',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=37, verbose_name='УИН'),
        ),
    ]
