# Generated by Django 4.1.7 on 2023-04-04 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_course_uin_coursemodule_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uin',
            field=models.CharField(default=uuid.uuid4, max_length=37, verbose_name='УИН'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='uin',
            field=models.CharField(default=uuid.uuid4, max_length=37, verbose_name='УИН'),
        ),
    ]
