# Generated by Django 4.1.7 on 2023-04-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=120, verbose_name='Краткое описание'),
        ),
    ]
