# Generated by Django 4.2 on 2023-04-09 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_googleform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Описание')),
                ('start_time', models.DateField(default=django.utils.timezone.now, verbose_name='Начало события')),
                ('end_time', models.DateField(default=django.utils.timezone.now, verbose_name='Окончание события')),
                ('hero_slider', models.BooleanField(default=False, verbose_name='Отображать на слайдере')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
