# Generated by Django 4.1.7 on 2023-04-02 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_course_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 21, 56, 24, 775661), verbose_name='Дата создания'),
        ),
    ]
