# Generated by Django 4.2 on 2023-04-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courseapp', '0005_siteevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevents',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='siteevents',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteevents',
            name='description',
            field=models.CharField(default='', max_length=350, verbose_name='Описание'),
        ),
    ]
