# Generated by Django 4.2 on 2023-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_siteevents_content_type_siteevents_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevents',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
