# Generated by Django 4.2 on 2023-04-11 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseapp', '0010_siteevents_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevents',
            name='speaker',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
